title: My Obsidian Vault
description: Notes and resources
remote_theme: just-the-docs/just-the-docs
# theme: just-the-docs   # Not supported on GitHub Pages
# baseurl: "/dsa_for_placements"  # Uncomment if your site is not at the root

# Optional: Sidebar navigation order and settings can be added here
# just_the_docs:
#   collections:
#     my_collection:
#       output: true
#       permalink: /:collection/:path/

exclude:
  - "*.pdf"
  - "*.jpg"
  - "*.png"
  - "*.jpeg"
  - "*.gif"
  - "*.exe"
  - "*.zip"
  - "*.tar"